apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: eduelevate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kartik2111/ed:backend
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: DB_URL
          value: "mongodb://mongodb-service:27017/project_eduelevate"
        # Reference individual secrets from the secret manifest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: eduelevate-secrets
              key: JWT_SECRET
        - name: RAZORPAY_KEY
          valueFrom:
            secretKeyRef:
              name: eduelevate-secrets
              key: RAZORPAY_KEY
        - name: RAZORPAY_SECRET
          valueFrom:
            secretKeyRef:
              name: eduelevate-secrets
              key: RAZORPAY_SECRET
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: eduelevate-secrets
              key: MAIL_USER
        - name: MAIL_PASS
          valueFrom:
            secretKeyRef:
              name: eduelevate-secrets
              key: MAIL_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: eduelevate
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30001 # Access via http://<node-ip>:30001
