apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: eduelevate
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: "Exists"
      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          ports:
            - name: metrics
              containerPort: 9100
          args:
            - --path.rootfs=/host
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($$|/)
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: rootfs
              mountPath: /host
              readOnly: true

      volumes:
        - name: rootfs
          hostPath:
            path: /
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: eduelevate
spec:
  type: ClusterIP
  selector:
    app: node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100

