apiVersion: v1
kind: Secret
metadata:
  name: eduelevate-secrets
  namespace: eduelevate
type: Opaque
stringData:
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
  RAZORPAY_KEY: ""
  RAZORPAY_SECRET: ""
  MAIL_USER: "kartikkushwaha2111@gmail.com"
  MAIL_PASS: "cwuymqwfbnpvmfrd"
  CLOUD_NAME: "dq2qgrkcb"
  API_KEY: "663874839683726"
  API_SECRET: "3qU9XvD-_Q9V2M1kA-P6w1T9mEg"
